# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration

name = "collection-manager"
client_id = "6d5593dbc8c7a2c4691d0a7b6ea29a18"
application_url = "https://shopify-json-frist-mongodb.vercel.app"
embedded = true

[access_scopes]
scopes = "write_products,read_products,write_content,read_content"

[auth]
redirect_urls = [
  "https://shopify-json-frist-mongodb.vercel.app/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testing-appx.myshopify.com"

[[app_navigation.links]]
label = "Collections"
destination = "/"

[[app_navigation.links]]
label = "Collection Groups"
destination = "/collection-groups.html"

[[app_navigation.links]]
label = "Collection Lists"
destination = "/collection-lists.html"

[[app_navigation.links]]
label = "Collection Types"
destination = "/collection-types.html"
